services:
  - type: rabbitmq
    name: rabbitmq
    plan: free
    healthCheckPath: /
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: ${RABBITMQ_USERNAME}
      - key: RABBITMQ_DEFAULT_PASS
        value: ${RABBITMQ_PASSWORD}

  - type: web
    name: mi-app-springboot
    env: docker
    plan: free
    buildCommand: docker build -t springboot-java21 .
    dockerfile: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: "health,info,prometheus,metrics"
      - key: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
        value: "true"
      - key: SPRING_RABBITMQ_HOST
        value: RABBITMQ_HOST
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
    secrets:
      - key: APP_ADMIN_USERNAME
        value: $APP_ADMIN_USERNAME
      - key: APP_ADMIN_PASSWORD
        value: $APP_ADMIN_PASSWORD
      - key: SPRING_RABBITMQ_USERNAME
        value: RABBITMQ_USERNAME
      - key: SPRING_RABBITMQ_PASSWORD
        value: RABBITMQ_PASSWORD
    healthCheckPath: /actuator/health
    dependsOn:
      - rabbitmq
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCpuUtilizationPercentage: 60
      targetMemoryUtilizationPercentage: 70