services:
  - type: redis
    name: my-redis
    plan: free
    ipAllowList:
    - source: "0.0.0.0/0"
  - type: web
    name: mi-app-springboot
    env: docker
    plan: free
    buildCommand: docker build -t springboot-java21 .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      - key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: "health,info,prometheus,metrics"
      - key: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
        value: "true"
      - key: SPRING_REDIS_HOST
        value: REDIS_HOST
      - key: SPRING_REDIS_PORT
        value: "6379"
      - key: APP_ADMIN_USERNAME
        value: APP_ADMIN_USERNAME
      - key: APP_ADMIN_PASSWORD
        value: APP_ADMIN_PASSWORD
    healthCheckPath: /actuator/health
    autoDeploy: true